### ISSUE TITLE
needs API documentation

### ISSUE THREAD

**Issue by medovina** [murmour/mparser#16]
As far as I can tell, this GitHub site has no API documentation for the mparser library.  It looks like there is some documentation at

   http://harnold.org/software/ocaml-base/doc/MParser.html

It seems like that should be integrated into this site, if this is indeed the new home of MParser.

**Comment by medovina** [comment]
This docmentation should be provided too:

http://harnold.org/software/ocaml-base/doc/MParser.Tokens.html

**Comment by medovina** [comment]
The links above now lead to 404 errors.  However, the API documentation is visible at

   https://ocaml.org/p/mparser/latest/doc/index.html

   https://ocaml.org/p/mparser-re/latest/doc/index.html

**Comment by medovina** [comment]
You marked this issue as completed, but I don't see links to the API documentation anywhere on https://github.com/murmour/mparser .  Am I just failing to see them?

**Comment by murmour** [comment]
Hello, Adam!

Since the docs at https://ocaml.org are generated automatically, as part of OPAM infrastructure, I expect that OCaml users will know where to find them. At least I never saw any links to these HTML docs mentioned in READMEs of other packages.

By the way, are these HTML docs truly useful? I'm curious because I always found it sufficient to read `*.mli`-s in my editor of choice. What are the advantages?

**Comment by medovina** [comment]
Hi Max,

thanks for your reply.  I thought a link from your README might be helpful, but if OCaml users generally know where to look, then maybe it doesn't matter.  In any case, I know where the pages are.  :)

I generally prefer the HTML documentation over the `.mli` files.  For one, it has nice sidebar hyperlinks that let me navigate to different sections easily.  I also think the formatting is nicer.

Thanks for maintaining mparser - it is an extremely useful library for me.  :)
